# Generated by Django 5.1.5 on 2025-01-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=100)),
                ('study_phase', models.CharField(choices=[('PHASE-I', 'PHASE-I'), ('PHASE-II', 'PHASE-II'), ('PHASE-III', 'PHASE-III'), ('PHASE-IV', 'PHASE-IV')], max_length=10)),
                ('study_sponser', models.CharField(max_length=100)),
                ('study_descrip', models.TextField()),
            ],
        ),
    ]
