# Generated by Django 5.1.5 on 2025-01-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studymgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='study_sponser',
            new_name='sponser_name',
        ),
    ]
