# Generated by Django 5.1.5 on 2025-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymgmt', '0002_rename_study_sponser_study_sponser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=4)),
                ('event', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
